
package org.example.Client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceClass", targetNamespace = "http://example.org/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServiceClass {
    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://example.org/ServiceClass/bonjourRequest", output = "http://example.org/ServiceClass/bonjourResponse")
    public String bonjour(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
